site_name: Kubernetes FAQ
site_url: https://katademy.github.io/kubernetes-faq
site_author: Icelyn Jennings
site_description: Learn Kubernetes, flashcards, CKA, CKAD, interview questions.

repo_url: https://github.com/katademy/kubernetes-faq/
repo_name: kubernetes-faq

theme:
  favicon: favicon.png
  icon:
    logo: material/kubernetes
  custom_dir: overrides
  features:
    - header.autohide
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/katademy
      name: katademy on Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/katademy
      name: katademy on GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/katademy
      name: katademy on LinkedIn
    - icon: fontawesome/brands/patreon
      link: https://patreon.com/icelynjennings
      name: icelynjennings on Patreon
    - icon: fontawesome/brands/paypal
      link: https://www.paypal.me/icelynjennings
      name: icelynjennings on PayPal

copyright: "&copy; 2020-2021 Icelyn Jennings"
